#----------------------------------------------------------------
#
#  Makefile for MEGAlib / cosima
#
#  Author: Andreas Zoglauer
#
#----------------------------------------------------------------


#----------------------------------------------------------------
# Commands:
#

clean:
		@rm -rf $(LB)/libcosima.*
		@if [ "$(G4SYSTEM)" != "" ]; then rm -rf $(LB)/$(G4SYSTEM); fi
		@if [ "$(G4SYSTEM)" != "" ]; then rm -rf $(BN)/$(G4SYSTEM); fi
		@rm -f $(BN)/Cosima
		@rm -f $(BN)/cosima
