#! /bin/bash

# doxy
#
# Copyright (C) by the MEGAlib contributors.
#
# This file is part of MEGAlib.
#
# MEGAlib is free software: you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# MEGAlib is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
# License (License.md) for more details.
#
# SPDX-License-Identifier: LGPL-3.0-or-later


rm -rf /tmp/doxygen
mkdir -p /tmp/doxygen

find src -follow -name '*.cxx' -exec cp {} /tmp/doxygen/ ';' 2> /dev/null
find src -follow -name '*.cpp' -exec cp {} /tmp/doxygen/ ';' 2> /dev/null
find src -follow -name '*.h' -exec cp {} /tmp/doxygen/ ';' 2> /dev/null
find src -follow -name '*.cc' -exec cp {} /tmp/doxygen/ ';' 2> /dev/null
find src -follow -name '*.hh' -exec cp {} /tmp/doxygen/ ';' 2> /dev/null

exit 0;

#! end
