#!/bin/bash

# This file is part of MEGAlib.
# Copyright (C) by Andreas Zoglauer.
#
# Please see the MEGAlib software license and documentation for more informations.

IsDebianClone=0
IsRedhatClone=0
IsOpenSuseClone=0


if [ -f /etc/os-release ]; then
  OS=`cat /etc/os-release | grep "^ID_LIKE\=" | awk -F= '{ print $2 }'`
  if [[ ${OS} == debian ]]; then
    IsDebianClone=1
  fi
fi

REQUIRED=""
TOBEINSTALLED=""

if [[ ${IsDebianClone} -eq 1 ]]; then
  
  # Check if this is Ubuntu:
  OS=`cat /etc/os-release | grep "^ID\=" | awk -F= '{ print $2 }'`
  #echo "OS: ${OS}"
  if [[ ${OS} == ubuntu ]]; then
    # Check if this is Ubuntu 14.04:
    VERSIONID=`cat /etc/os-release | grep "^VERSION_ID\=" | awk -F= '{ print $2 }'`
    VERSIONID=${VERSIONID//\"/}
    #echo "VERSION: ${VERSIONID}"
    if [[ ${VERSIONID} == 14.04 ]]; then
      REQUIRED="git gawk dpkg-dev make g++ gcc gdb valgrind binutils libx11-dev libxpm-dev libxft-dev libxext-dev libssl-dev libpcre3-dev libglu1-mesa-dev libglew-dev libftgl-dev libmysqlclient-dev libfftw3-dev graphviz-dev libavahi-compat-libdnssd-dev libldap2-dev python-dev libxml2-dev libkrb5-dev libgsl0-dev cmake libxmu-dev curl"
    elif [[ ${VERSIONID} == 16.04 ]]; then
      REQUIRED="git gawk dpkg-dev make g++ gcc gdb valgrind binutils libx11-dev libxpm-dev libxft-dev libxext-dev libssl-dev libpcre3-dev libglu1-mesa-dev libglew-dev libftgl-dev libmysqlclient-dev libfftw3-dev graphviz-dev libavahi-compat-libdnssd-dev libldap2-dev python-dev libxml2-dev libkrb5-dev libgsl-dev cmake libxmu-dev curl doxygen libblas-dev liblapack-dev"
    elif [[ ${VERSIONID} == 18.04 ]]; then
      REQUIRED="git gawk dpkg-dev make g++ gcc gdb valgrind binutils libx11-dev libxpm-dev libxft-dev libxext-dev libssl-dev libpcre3-dev libglu1-mesa-dev libglew-dev libftgl-dev libmysqlclient-dev libfftw3-dev graphviz-dev libavahi-compat-libdnssd-dev libldap2-dev python-dev libxml2-dev libkrb5-dev libgsl-dev cmake libxmu-dev curl doxygen libblas-dev liblapack-dev doxygen expect"
    fi
  fi
  
  #echo "Required: ${REQUIRED}"
  if [[ "${REQUIRED}" == "" ]]; then exit 0; fi
    
  # Check if each of the packages exists:
  for PACKAGE in ${REQUIRED}; do 
    # Check if the file is installed
    STATUS=`dpkg-query -Wf'${db:Status-abbrev}' ${PACKAGE} 2>/dev/null | grep '^i'`
    #echo "${PACKAGE}: >${STATUS}<"
    if [[ "${STATUS}" == "" ]]; then
      # Check if it exists at all:
      echo "Not installed: ${PACKAGE}"
      TOBEINSTALLED="${TOBEINSTALLED} ${PACKAGE}"

      #STATUS=`apt-cache pkgnames ${PACKAGE} 2>/dev/null`
      #if [[ "${STATUS}" != "" ]]; then
      #  TOBEINSTALLED="${TOBEINSTALLED} ${PACKAGE}"
      #fi
    fi
  done
  
  if [[ "${TOBEINSTALLED}" != "" ]]; then
    echo " "
    echo "Do the following to install all required packages:"
    echo "sudo apt-get update; sudo apt-get install ${TOBEINSTALLED}"
    echo " "
    exit 1;
  else 
    echo "All required packages are already installed! However, this script is only tested to work for Ubuntu 14.04 & 16.06."
  fi
fi


exit 0
