#!/bin/bash

# This file is part of MEGAlib.
# Copyright (C) by Andreas Zoglauer.
#
# Please see the MEGAlib software license and documentation for more informations.


# The compiler test in version 2.28 here is just a dummy for backward compatibility of the setup script

exit 0
