#!/bin/bash

# configure_misctools
#
# Copyright (C) by the MEGAlib contributors.
#
# This file is part of MEGAlib.
#
# MEGAlib is free software: you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# MEGAlib is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
# License (License.md) for more details.
#
# SPDX-License-Identifier: LGPL-3.0-or-later



Convert=`type -P convert`
Expect=`type -P expect`
Doxygen=`type -P doxygen`

ReturnCode=0

if ([ "${Doxygen}" != "" ]); then
    echo "Found doxygen: ${Doxygen}"
else
    echo "Not found: \"doxygen\""
    echo "   -> You will not be able to create MEGAlib source code documentation"
    ReturnCode=1
fi;

if ([ "${Convert}" != "" ]); then
    echo "Found convert: ${Convert}"
else
    echo "Not found: \"convert\""
    echo "   -> You will not be able to create animations with Mimrec"
    ReturnCode=1
fi;

if ([ "${Expect}" != "" ]); then
    echo "Found expect: ${Expect}"
else
    echo "Not found: \"expect\""
    echo "   -> You will not be able to use all options of the pipeline script"
    ReturnCode=1
fi;

exit ${ReturnCode}
