#!/bin/bash

# configure_checkpath
#
# Copyright (C) by the MEGAlib contributors.
#
# This file is part of MEGAlib.
#
# MEGAlib is free software: you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# MEGAlib is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
# License (License.md) for more details.
#
# SPDX-License-Identifier: LGPL-3.0-or-later


help() {
  echo ""
  echo "MEGAlib program/library existance check script"
  echo "Usage: $0 [\"lib\" or \"exe\"] [program or library name]";
  echo "Return: 1 in case of success, 0 otherwise"
  echo ""
}

# Test if all options are given:
if [ $# -lt 2 ] ; then
  echo ""
  echo "Error: You must specify the type of object (\"lib\" or \"exe\") and the program/library name";
  help; 
  exit 0;
fi


FileType=$1
Program=$2
Folders=()
if [ "${FileType}" == "exe" ]; then
  Folders=( `echo $PATH | tr ':' ' '` )
elif [ "${FileType}" == "lib" ]; then
  Folders=( `echo ${LD_LIBRARY_PATH} ${DYLD_LIBRARY_PATH} | tr ':' ' '` )
else 
  echo ""
  echo "Error: You must specify the type of object as \"lib\" or \"exe\"";
  help; 
  exit 0;
fi


# On El Capitan ${LD_LIBRARY_PATH} is not transfered to subshells, thus protect
if [ "${FileType}" == "exe" ] && [ "${PATH}" == "" ]; then
  exit 1;
fi
if [ "${FileType}" == "lib" ] && [ "${LD_LIBRARY_PATH}" == "" ]; then
  exit 1;
fi


Found=0
for folder in ${Folders[@]}; do
  #echo "Checking folder: ${folder}" 
  if (`test ! -d ${folder}`); then continue; fi
  cd ${folder}
  for file in `ls`; do
    if [ "${FileType}" == "exe" ]; then 
      if [ "${file}" == "${Program}" ]; then
        if ( `test -x ${file}` ); then      
          #echo "Found: ${file} == ${Program} in ${folder}"
          Found=1;
          break;
        fi
      fi
    fi
    if [ "${FileType}" == "lib" ]; then 
      #echo "Looking for ${Program}.[a,so,dylib]"
      if ( [ "${file}" == "${Program}.a" ] || [ "${file}" == "${Program}.so" ] || [ "${file}" == "${Program}.dylib" ] ); then
         #echo "Found: ${file} == ${Program} in ${folder}"
         if ( `test -r ${file}` ); then      
          #echo "Found: ${file} == ${Program} in ${folder} with read access"
          Found=1;
          break;
        fi
      fi
    fi
  done
  if [ ${Found} -eq 1 ]; then
    break;
  fi
done

#echo "Return code: ${Found}"

exit ${Found};

