#!/bin/bash

TOOLS_ROOT="cmake OpenBLAS davix expat giflib git gl2ps gmp graphviz gsl jpeg libgcc libpng libxml2 lz4 lzma openssl pcre py38-gnureadline py38-jupyter py38-metakernel py38-numpy python38 tbb tiff vdt xrootd xxhashlib xz"

TOOLS_GEANT4="cmake pkgconfig zlib"

TOOLS_MEGALIB="doxygen cfitsio"

echo "This script will install the following programs/libraries:"
echo "${TOOLS_ROOT} ${TOOLS_GEANT4} ${TOOLSMEGALIB}"
echo " "
echo "This will require sudo priviledges. Feel free to take a look at the source code if you are cautious."

for TOOL in ${TOOLS_ROOT} ${TOOLS_GEANT4} ${TOOLSMEGALIB}; do
  sudo port -N install ${TOOL}
done

sudo port select --set python python38
sudo port select --set python3 python38


exit 1
