# Makefile.gcc_optimizations
#
# Copyright (C) by the MEGAlib contributors.
#
# This file is part of MEGAlib.
#
# MEGAlib is free software: you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# MEGAlib is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
# License (License.md) for more details.
#
# SPDX-License-Identifier: LGPL-3.0-or-later


# For improved execution performance with the GNU gcc compiler (4.3 or higher) 
# you might also test one of the following flags.
#
# On an Intel Pentium M:
# OPT += -march=native
# 
# On an Intel Pentium 4/Xeon:
# OPT += -march=native
# 
# On an Intel Core 2 Duo:
# OPT += -march=native
#
# On an Intel Atom (requires 11.0 or higher):
# OPT += -O1 -msse3 -march=core2 -mfpmath=sse
#
# Remember also to compile Geant4/ROOT with those options, otherwise you only 
# speed up the MEGAlib elements but not the libraries which ROOT uses
