/*
 * MGUIExposure.cxx
 *
 *
 * Copyright (C) by Andreas Zoglauer.
 * All rights reserved.
 *
 *
 * This code implementation is the intellectual property of
 * Andreas Zoglauer.
 *
 * By copying, distributing or modifying the Program (or any work
 * based on the Program) you indicate your acceptance of this statement,
 * and all its terms.
 *
 */


////////////////////////////////////////////////////////////////////////////////
//
// MGUIExposure
//
////////////////////////////////////////////////////////////////////////////////


// Include the header:
#include "MGUIExposure.h"

// Standard libs:

// ROOT libs:

// MEGAlib libs:


////////////////////////////////////////////////////////////////////////////////


#ifdef ___CINT___
ClassImp(MGUIExposure)
#endif


////////////////////////////////////////////////////////////////////////////////


MGUIExposure::MGUIExposure(const TGWindow* Parent, const TGWindow* Main, 
                           MSettingsImaging* Settings)
  : MGUIDialog(Parent, Main)
{
  // standard constructor

  m_Settings = Settings;

  // use hierarchical cleaning
  SetCleanup(kDeepCleanup);

  Create();
}


////////////////////////////////////////////////////////////////////////////////


MGUIExposure::~MGUIExposure()
{
  // kDeepCleanup is activated
}


////////////////////////////////////////////////////////////////////////////////


void MGUIExposure::Create()
{
  // Create the main window

  // We start with a name and an icon...
  SetWindowName("Exposure / Sensitivity matrix / Efficiency --- same thing different names");  

  AddSubTitle("Select the file, which contains the raw efficiency data, generated by the responsecreator:"); 

  m_FileSelectorLayout = new TGLayoutHints(kLHintsLeft | kLHintsTop | kLHintsExpandX, 20, 20, 10, 2);
  m_FileSelector = new MGUIEFileSelector(this, "Choose a file (assume flat exposure, if the box is empty):");
  m_FileSelector->SetFileType("Response file", "*.rsp");
  m_FileSelector->SetFileType("Gzip'ed response file", "*.rsp.gz");
  
  if (m_Settings->GetExposureMode() == MExposureMode::CalculateFromEfficiency) {
    m_FileSelector->SetFileName(m_Settings->GetExposureEfficiencyFile());
  }

  AddFrame(m_FileSelector, m_FileSelectorLayout);


  AddButtons();

  PositionWindow(GetDefaultWidth(), GetDefaultHeight(), false);
  
  // and bring it to the screen.
  MapSubwindows();
  MapWindow();  

  Layout();
 
  return;
}


////////////////////////////////////////////////////////////////////////////////


bool MGUIExposure::OnApply()
{
  // The Apply button has been pressed

  m_Settings->SetExposureEfficiencyFile(m_FileSelector->GetFileName());
  if (m_FileSelector->GetFileName().IsEmpty() == false) {
    m_Settings->SetExposureMode(MExposureMode::CalculateFromEfficiency);
  } else {
    m_Settings->SetExposureMode(MExposureMode::Flat);
  }
  
  return true;
}


// MGUIExposure: the end...
////////////////////////////////////////////////////////////////////////////////
